name: Sync to Gitee

on:
    push:
        branches: [ master ]
    release:
        types: [created, edited]
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.GITEE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan gitee.com >> ~/.ssh/known_hosts

            - name: Push to Gitee
              run: |
                  git remote add gitee git@gitee.com:jiangehenpi/docker-php-extension-installer.git
                  git push --all --force gitee
                  git push --tags --force gitee
            
            # 新增步骤：获取最新标签
            - name: Get latest tag
              id: get_latest_tag
              run: |
                  git fetch --tags
                  TAG=$(git describe --tags --abbrev=0)
                  echo "tag=$TAG" >> $GITHUB_OUTPUT
            
            # 修改后的步骤4：始终执行
            - name: Sync Releases to Gitee
              env:
                  GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
                  RELEASE_TAG: ${{ github.event.release.tag_name || steps.get_latest_tag.outputs.tag }}
                  RELEASE_NAME: ${{ github.event.release.name || 'Release ${{ steps.get_latest_tag.outputs.tag }}' }}
                  RELEASE_BODY: ${{ github.event.release.body || 'Auto-generated by CI/CD' }}
              run: |
                  # 安装依赖
                  sudo apt-get -qq update && sudo apt-get -qq install -y jq
                  
                  # 删除旧 Release
                  curl -sL -X DELETE \
                    "https://gitee.com/api/v5/repos/jiangehenpi/docker-php-extension-installer/releases/tags/$RELEASE_TAG" \
                    -H "Authorization: token $GITEE_TOKEN" \
                    || true
                  
                  # 创建新 Release
                  response=$(curl -sL -X POST \
                    "https://gitee.com/api/v5/repos/jiangehenpi/docker-php-extension-installer/releases" \
                    -H "Authorization: token $GITEE_TOKEN" \
                    -H "Content-Type: application/json" \
                    -d "{
                      \"tag_name\": \"$RELEASE_TAG\",
                      \"name\": \"$RELEASE_NAME\",
                      \"body\": \"$RELEASE_BODY\"
                    }")
                  
                  # 同步附件（仅在 release 事件中有附件）
                  if [[ "${{ github.event_name }}" == "release" ]]; then
                    assets_url=${{ github.event.release.assets_url }}
                    assets=$(curl -sL "$assets_url" | jq -r '.[] | .url')
                    gitee_release_id=$(echo "$response" | jq -r '.id')
                  
                    for asset_url in $assets; do
                      asset_name=$(basename "$asset_url")
                      curl -sL -O "$asset_url" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
                      curl -sL -X POST \
                        "https://gitee.com/api/v5/repos/jiangehenpi/docker-php-extension-installer/releases/$gitee_release_id/upload" \
                        -H "Authorization: token $GITEE_TOKEN" \
                        -F "file=@$asset_name"
                    done
                  fi
